module.exports = Object.freeze({
	control: {
		START_SYSEX: 0xF0,
		UARM_CODE: 0xAA,
		END_SYSEX: 0xF7
	},
	command: {
		READ_ANGLE: 0x10,
		WRITE_ANGLE: 0x11,
		READ_COORDS: 0x12,
		WRITE_COORDS: 0x13,
		READ_DIGITAL: 0x14,
		WRITE_DIGITAL: 0x15,
		READ_ANALOG: 0x16,
		WRITE_ANALOG: 0x17,
		READ_EEPROM: 0x1A,
		WRITE_EEPROM: 0x1B,
		SERVO_STATUS: 0x1C,
		PUMP_STATUS: 0x1D,
		GRIPPER_STATUS: 0x20,
		WRITE_STRETCH: 0x1E,
		WRITE_LEFT_RIGHT_ANGLE: 0x1F,
		READ_SERIAL_NUMBER: 0x21,
		WRITE_SERIAL_NUMBER: 0x22,
		REPORT_LIBRARY_VERSION: 0x23,
		BUZZER_ALERT: 0x24
	},
	arguments: {
		READ_ANGLE: ['SERVO', 'FLAG'],
		WRITE_ANGLE: ['SERVO', 'ANGLE', 'FLAG'],
		READ_COORDS: null,
		WRITE_COORDS: ['COORD', 'COORD', 'COORD', 'COORD', 'FLAG', 'TIME', 'FLAG', 'FLAG'],
		READ_DIGITAL: ['PIN', 'FLAG'],
		WRITE_DIGITAL: ['PIN', 'FLAG'],
		READ_ANALOG: ['PIN'],
		WRITE_ANALOG: ['PIN', 'ANALOG'],
		READ_EEPROM: ['DATA_TYPE', 'ANALOG'],
		WRITE_EEPROM: ['DATA_TYPE', 'ANALOG', 'ANY'],
		SERVO_STATUS: ['SERVO', 'FLAG'],
		PUMP_STATUS: ['FLAG'],
		GRIPPER_STATUS: ['FLAG'],
		WRITE_STRETCH: ['COORD', 'COORD'],
		WRITE_LEFT_RIGHT_ANGLE: ['ANGLE', 'ANGLE'],
		BUZZER_ALERT: ['NUMBER', 'NUMBER', 'NUMBER']
	}
});
// Joi.any().forbidden()
// I don't care about these
// "READ_SERIAL_NUMBER" : [],
// "WRITE_SERIAL_NUMBER" : [FB_BYTE,FB_BYTE,FB_BYTE,FB_BYTE,FB_BYTE,FB_BYTE,FB_BYTE,FB_BYTE,FB_BYTE,FB_BYTE,FB_BYTE,FB_BYTE,FB_BYTE,FB_BYTE,],
// "REPORT_LIBRARY_VERSION" : []
